package pages.model;

public enum Categories {
	
	AIRE_LIBRE, ALIMENTOS_CONGELADOS, ALMACEN, AUTOMOTOR, BAZAR, BEBIDAS_CON_ALCOHOL, BEBIDAS_SIN_ALCOHOL, BLANCO_Y_MANTELERIA, CALZADO_Y_MARROQUINERIA, CARNICERIA, COMIDAS_ELABORADAS, ELECTRODOMESTICOS, FERRETERIA, FIAMBRERIA, FRUTAS_Y_VERDURAS, GASTRONOMIA, ILUMINACION, JARDINERIA,KOSHER, LACTEOS, LIBRERIA, LIBROS, LIMPIEZA, MAMAS_Y_BEBES, MASCOTAS, MUEBLES, PANADERIA_Y_GOLOSINAS, PASTAS, PERFUMERIA, PESCADOS_Y_MARISCOS, PILAS_Y_ACCESORIOS, SABORES_DEL_MUNDO;

}
